---
title: "gaps"
author: "Julie Jung"
date: "July 13, 2018"
output: pdf_document
---

Data analysis from gap experiment (conducted summer 2017)

```{r}
setwd('/Users/juliejung/Documents/GitHub/gaps') 
```

```{r}
library(R.matlab)
library(ggplot2)
library(MASS)
library(multcomp)
library("stargazer")
library("knitr")
library("dplyr")
library(sciplot) 
```
#trying to read hatching times from .mat files

```{r}

#hatching times for stimulus 16 (control), experiment 1
hatching_times_16_1 <- readMat("/Users/juliejung/Documents/GitHub/gaps/hatchingtimes(_stimulus_experiment)//hatching_times_16_1.mat")

#hatching times for stimulus 16 (control), experiment 2
hatching_times_16_2 <- readMat("/Users/juliejung/Documents/GitHub/gaps/hatchingtimes(_stimulus_experiment)//hatching_times_16_2.mat")

#plot
## this is tricky! --> easier to do in matlab!
```

#Exps 1-3
```{r}
hatching_data<-read.csv(file="hatching_data.csv")
```

Subset out the test data
```{r}
subset_hatching <- subset(hatching_data, hatching_data$Subset.Hatching.Data=="Data")
str(subset_hatching) 

#subset_hatching_times <- subset(hatching_data, hatching_data$Subset.Hatching.Times.Data=="Data")
```

Split into Experiments 1-3
```{r}
Experiment1 <- subset(hatching_data, hatching_data$Experiment==1)
Experiment2 <- subset(hatching_data, hatching_data$Experiment==2)
Experiment3 <- subset(hatching_data, hatching_data$Experiment==3)
```


#Exp 1
```{r}
Exp1Table<-
  Experiment1 %>%
  group_by(Stimulus) %>%
  summarize(count = n(),
            mean = mean(Proportion.Hatched),
            SD = sd(Proportion.Hatched), 
            SE = sd(Proportion.Hatched)/sqrt(n())
            )
kable(Exp1Table,title="Mean & SD & SE",digits=4)
```

```{r}
ggplot(Experiment1, aes(x=as.factor(Stimulus), y=Proportion.Hatched)) + 
  geom_boxplot(data=Experiment1, size=2) +
  ylab("Proportion of tray hatched\n")+
  theme_bw(20) +
  xlab("\n Stimulus")+
  theme(legend.position="none")
```

```{r}
lm1<-lm(Proportion.Hatched~Stimulus, data=Experiment1)
lm2<-glht(lm1, linfct=mcp(Stimulus="Tukey"))
summary(lm2)
cld(lm2) 

```

#Exp 2
```{r}
Exp2Table<-
  Experiment2 %>%
  group_by(Stimulus) %>%
  summarize(count = n(),
            mean = mean(Proportion.Hatched),
            SD = sd(Proportion.Hatched), 
            SE = sd(Proportion.Hatched)/sqrt(n())
            )
kable(Exp2Table,title="Mean & SD & SE",digits=4)
```

```{r}
ggplot(Experiment2, aes(x=as.factor(Stimulus), y=Proportion.Hatched)) + 
  geom_boxplot(data=Experiment2, size=2) +
  ylab("Proportion of tray hatched\n")+
  theme_bw(20) +
  xlab("\n Stimulus")+
  theme(legend.position="none")
```

```{r}
lm1<-lm(Proportion.Hatched~Stimulus, data=Experiment2)
lm2<-glht(lm1, linfct=mcp(Stimulus="Tukey"))
summary(lm2)
cld(lm2) 
```

#Exp 3
```{r}
Exp3Table<-
  Experiment3 %>%
  group_by(Stimulus) %>%
  summarize(count = n(),
            mean = mean(Proportion.Hatched),
            SD = sd(Proportion.Hatched), 
            SE = sd(Proportion.Hatched)/sqrt(n())
            )
kable(Exp3Table,title="Mean & SD & SE",digits=4)
```

```{r}
ggplot(Experiment3, aes(x=as.factor(Stimulus), y=Proportion.Hatched)) + 
  geom_boxplot(data=Experiment3, size=2) +
  ylab("Proportion of tray hatched\n")+
  theme_bw(20) +
  xlab("\n Stimulus")+
  theme(legend.position="none")
```


```{r}
lm1<-lm(Proportion.Hatched~Stimulus, data=Experiment3)
lm2<-glht(lm1, linfct=mcp(Stimulus="Tukey"))
summary(lm2)
cld(lm2) 
```

#Exp 4
```{r}
gap.df<-read.csv(file="gap.csv")
```

```{r}
str(gap.df)
quantile(gap.df$PBKtimehr)
quantile(gap.df$EP5)
```
```{r}
PropHTable<-
  gap.df %>%
  group_by(Gap) %>%
  summarize(count = n(),
            mean = mean(PropH),
            SD = sd(PropH), 
            SE = sd(PropH)/sqrt(n())
            )
#indivsperclutch$AgeGroup <- 5.2
kable(PropHTable,title="Mean & SD & SE",digits=4)
```

```{r}
ggplot(gap.df, aes(x=as.factor(Gap), y=PropH)) + 
  geom_boxplot(data=gap.df, size=2) +
  ylab("Proportion of tray hatched\n")+
  theme_bw(20) +
  xlab("\n Gap length (sec)")+
  theme(legend.position="none")

```

```{r}
gap.df$Gap<-as.factor(gap.df$Gap)
lm1<-lm(PropH~Gap, data=gap.df)
lm2<-glht(lm1, linfct=mcp(Gap="Tukey"))
summary(lm2)
cld(lm2) 

```


```{r}
## Gives count, mean, standard deviation, standard error of the mean, and confidence interval (default 95%).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   groupvars: a vector containing names of columns that contain grouping variables
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
  library(plyr)
  
  # New version of length which can handle NA's: if na.rm==T, don't count them
  length2 <- function (x, na.rm=FALSE) {
    if (na.rm) sum(!is.na(x))
    else       length(x)
  }
  
  # This does the summary. For each group's data frame, return a vector with
  # N, mean, and sd
  datac <- ddply(data, groupvars, .drop=.drop,
                 .fun = function(xx, col) {
                   c(N    = length2(xx[[col]], na.rm=na.rm),
                     mean = mean   (xx[[col]], na.rm=na.rm),
                     sd   = sd     (xx[[col]], na.rm=na.rm)
                   )
                 },
                 measurevar
  )
  
  # Rename the "mean" column    
  datac <- rename(datac, c("mean" = measurevar))
  
  datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean
  
  # Confidence interval multiplier for standard error
  # Calculate t-statistic for confidence interval: 
  # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
  ciMult <- qt(conf.interval/2 + .5, datac$N-1)
  datac$ci <- datac$se * ciMult
  
  return(datac)
}
```


```{r}
gapSE <- summarySE(gap.df, measurevar="PropH", groupvars=c("Gap", "AvgStage"), na.rm=T)

ggplot(gapSE, aes(x=as.factor(Gap), y=PropH)) + 
  geom_boxplot(data=gapSE, size=2) +
  #geom_errorbar(aes(ymin=PropH-se, ymax=PropH+se), width=.1) +
  ylab("Proportion of tray hatched\n")+
  theme_bw(20) +
  xlab("\n Gap length (sec)")+
  theme(legend.position="none")

ggplot(gap.df, aes(x=AvgStage, y=PropH)) + 
  geom_point(data=gap.df, size=3) +
  ylab("Proportion of tray hatched\n")+
  theme_bw(20) +
  xlab("\n Developmental stage")+
  theme(legend.position="none")

```



```{r}
gap0 <- subset(gap.df, Gap == 0)
gap30 <- subset(gap.df, Gap == 30)
gap45 <- subset(gap.df, Gap == 45)
gap60 <- subset(gap.df, Gap == 60)
```



```{r}

```