function plotscript2 (data_subset, threshold)

set(gca, 'xscale', 'log');
set(gca, 'yscale', 'log');
set(gca, 'ZlimMode', 'manual');
zlim([0,1]);
xlabel('min interval (seconds)');
ylabel('min duration (seconds)');
zlabel('percent');
t = strcat('range = ', num2str(threshold));
title(t);
grid on;
view(3);
hold on;

num_rows = size(data_subset, 1);

for i = 1:num_rows
    if (i < num_rows)
        if (mod(i, 10) ~= 0)
            plot3([data_subset(i,2), data_subset(i+1,2)], ...
                [data_subset(i,3), data_subset(i+1,3)], ...
                [data_subset(i,4), data_subset(i+1,4)], ...
                '-*r');
            
            plot3([data_subset(i,2), data_subset(i+1,2)], ...
                [data_subset(i,3), data_subset(i+1,3)], ...
                [data_subset(i,5), data_subset(i+1,5)], ...
                '-*g');
            
            plot3([data_subset(i,2), data_subset(i+1,2)], ...
                [data_subset(i,3), data_subset(i+1,3)], ...
                [data_subset(i,6), data_subset(i+1,6)], ...
                '-*b');
        end
    end
     
    if (i > 10)
        plot3([data_subset(i,2), data_subset(i-10,2)], ...
              [data_subset(i,3), data_subset(i-10,3)], ...
              [data_subset(i,4), data_subset(i-10,4)], ...
              '-*r'); 
        plot3([data_subset(i,2), data_subset(i-10,2)], ...
              [data_subset(i,3), data_subset(i-10,3)], ...
              [data_subset(i,5), data_subset(i-10,5)], ...
              '-*g'); 
        plot3([data_subset(i,2), data_subset(i-10,2)], ...
              [data_subset(i,3), data_subset(i-10,3)], ...
              [data_subset(i,6), data_subset(i-10,5)], ...
              '-*b'); 
    end
end

hold off;
